import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: { autoRefreshToken: false, persistSession: false },
});

interface Scripture {
  book: string;
  chapter: number;
  verse_start: number;
  verse_end?: number | null;
  text: string;
  tags: string[];
  testament: "old" | "new";
}

const scriptures: Scripture[] = [
  // FAITH
  { book: "Romans", chapter: 10, verse_start: 9, verse_end: 10, text: "Because if you confess with your mouth that Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved. For with the heart one believes, resulting in righteousness, and with the mouth one confesses, resulting in salvation.", tags: ["faith", "salvation"], testament: "new" },
  { book: "Romans", chapter: 8, verse_start: 38, verse_end: 39, text: "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor any other created thing, will be able to separate us from the love of God, which is in Christ Jesus our Lord.", tags: ["faith", "love"], testament: "new" },
  { book: "Romans", chapter: 4, verse_start: 20, verse_end: 21, text: "Yet, looking at the promise of God, he didn't waver through unbelief, but was strengthened by faith, giving glory to God, and being fully assured that what he had promised, he was able also to perform.", tags: ["faith"], testament: "new" },
  { book: "Romans", chapter: 12, verse_start: 3, text: "For I say, through the grace that was given me, to every man who is among you, not to think of himself more highly than he ought to think; but to think reasonably, as God has dealt to each one a measure of faith.", tags: ["faith"], testament: "new" },
  { book: "Galatians", chapter: 2, verse_start: 16, verse_end: 20, text: "knowing that a man is not justified by works of the law but through faith in Jesus Christ, even we have believed in Christ Jesus, that we might be justified by faith in Christ, and not by works of the law; for by works of the law no flesh will be justified. But if, while seeking to be justified in Christ, we ourselves were also found sinners, is Christ a servant of sin? Certainly not! For if I rebuild what I tore down, I prove myself a transgressor.", tags: ["faith", "grace"], testament: "new" },
  { book: "Galatians", chapter: 3, verse_start: 26, verse_end: 29, text: "For you are all sons of God, through faith, in Christ Jesus. As many of you as were baptized into Christ have put on Christ. There is neither Jew nor Greek, there is neither slave nor free man, there is neither male nor female; for you are all one in Christ Jesus. If you are Christ's, then you are Abraham's seed, and heirs according to the promise.", tags: ["faith"], testament: "new" },
  { book: "Ephesians", chapter: 2, verse_start: 8, verse_end: 10, text: "For by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, that no one would boast. For we are his workmanship, created in Christ Jesus for good works, which God prepared beforehand, that we should walk in them.", tags: ["faith", "grace"], testament: "new" },
  { book: "2 Corinthians", chapter: 5, verse_start: 7, text: "For we walk by faith, not by sight.", tags: ["faith"], testament: "new" },
  { book: "Hebrews", chapter: 11, verse_start: 1, text: "Now faith is the assurance of things hoped for, the evidence of things not seen.", tags: ["faith", "hope"], testament: "new" },
  { book: "Hebrews", chapter: 11, verse_start: 6, text: "Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists, and that he is a rewarder of those who seek him.", tags: ["faith"], testament: "new" },
  { book: "1 John", chapter: 5, verse_start: 4, verse_end: 5, text: "For whatever is born of God overcomes the world; and this is the victory that has overcome the world, our faith. Who is the one who overcomes the world, but he who believes that Jesus is the Son of God?", tags: ["faith"], testament: "new" },
  { book: "James", chapter: 2, verse_start: 17, verse_end: 18, text: "Even so faith, if it has no works, is dead in itself. But someone may say, You have faith, and I have works. Show me your faith without your works, and I will show you my faith by my works.", tags: ["faith"], testament: "new" },

  // PRAYER
  { book: "Philippians", chapter: 4, verse_start: 6, verse_end: 7, text: "Be anxious for nothing, but in everything, by prayer and petition, with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.", tags: ["prayer", "peace"], testament: "new" },
  { book: "Matthew", chapter: 7, verse_start: 7, verse_end: 11, text: "Ask, and it will be given to you. Seek, and you will find. Knock, and it will be opened to you. For everyone who asks receives. He who seeks finds. To him who knocks it will be opened. Or who among you, if his son asks for bread, will give him a stone? Or if he asks for a fish, will give him a serpent? If you then, being evil, know how to give good gifts to your children, how much more will your Father in heaven give good things to those who ask him?", tags: ["prayer"], testament: "new" },
  { book: "Matthew", chapter: 6, verse_start: 9, verse_end: 13, text: "Therefore pray like this: Our Father in heaven, may your name be kept holy. May your Kingdom come. May your will be done on earth, as it is in heaven. Give us today our daily bread. Forgive us our debts, as we also forgive our debtors. Bring us not into temptation, but deliver us from the evil one. For yours is the Kingdom, the power, and the glory forever. Amen.", tags: ["prayer"], testament: "new" },
  { book: "Luke", chapter: 18, verse_start: 1, text: "He also spoke a parable to them, that they need to always pray and not give up.", tags: ["prayer"], testament: "new" },
  { book: "1 Thessalonians", chapter: 5, verse_start: 16, verse_end: 18, text: "Always rejoice, pray without ceasing, in everything give thanks. For this is the will of God in Christ Jesus concerning you.", tags: ["prayer"], testament: "new" },
  { book: "Colossians", chapter: 4, verse_start: 2, verse_end: 4, text: "Continue steadfastly in prayer, being watchful in it with thanksgiving, praying at the same time for us, that God may open to us a door for the word, to speak the mystery of Christ, for which I am also in chains, that I may make it clear, as I ought to speak.", tags: ["prayer"], testament: "new" },
  { book: "Romans", chapter: 12, verse_start: 12, text: "rejoicing in hope, enduring in troubles, continuing steadfastly in prayer", tags: ["prayer", "hope"], testament: "new" },
  { book: "James", chapter: 5, verse_start: 16, verse_end: 18, text: "Confess your offenses to one another, and pray for one another, that you may be healed. The insistent prayer of a righteous person is very powerful in its effect. Elijah was a man with a nature like ours, and he prayed earnestly that it would not rain, and it didn't rain on the land for three years and six months. He prayed again, and the sky gave rain, and the land produced its fruit.", tags: ["prayer"], testament: "new" },
  { book: "1 John", chapter: 5, verse_start: 14, verse_end: 15, text: "This is the confidence that we have in him, that if we ask anything according to his will, he hears us. And if we know that he hears us, whatever we ask, we know that we have the petitions that we have asked of him.", tags: ["prayer", "trust"], testament: "new" },
  { book: "John", chapter: 14, verse_start: 13, verse_end: 14, text: "Whatever you will ask in my name, I will do it, that the Father may be glorified in the Son. If you will ask anything in my name, I will do it.", tags: ["prayer"], testament: "new" },
  { book: "Jeremiah", chapter: 33, verse_start: 3, text: "Call to me, and I will answer you, and will show you great and hidden things, which you haven't known.", tags: ["prayer"], testament: "old" },
  { book: "Psalm", chapter: 145, verse_start: 18, text: "Yahweh is near to all those who call on him, to all who call on him in truth.", tags: ["prayer"], testament: "old" },

  // HOPE
  { book: "Romans", chapter: 15, verse_start: 13, text: "Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope, in the power of the Holy Spirit.", tags: ["hope", "peace", "faith"], testament: "new" },
  { book: "Psalm", chapter: 39, verse_start: 7, verse_end: 8, text: "Now, Lord, what do I wait for? My hope is in you. Deliver me from all my transgressions. Don't make me the reproach of the foolish.", tags: ["hope", "trust"], testament: "old" },
  { book: "Psalm", chapter: 62, verse_start: 5, verse_end: 8, text: "My soul, wait in silence for God alone, for my hope is from him. He alone is my rock and my salvation, my stronghold. I will not be shaken. My salvation and my honor is with God, my rock, and my refuge. Trust in him at all times, you people. Pour out your heart before him. God is a refuge for us.", tags: ["hope", "trust", "salvation"], testament: "old" },
  { book: "Lamentations", chapter: 3, verse_start: 24, verse_end: 26, text: "Yahweh is my portion, says my soul; therefore I will hope in him. Yahweh is good to those who wait for him, to the soul that seeks him. It is good that one should hope and wait quietly for the salvation of Yahweh.", tags: ["hope", "salvation"], testament: "old" },
  { book: "Jeremiah", chapter: 29, verse_start: 11, text: "For I know the thoughts that I think toward you, says Yahweh, thoughts of peace, and not of evil, to give you hope in your latter end.", tags: ["hope", "peace"], testament: "old" },
  { book: "Proverbs", chapter: 23, verse_start: 18, text: "Surely there is a future, and your hope will not be cut off.", tags: ["hope", "wisdom"], testament: "old" },
  { book: "Psalm", chapter: 146, verse_start: 5, text: "Happy is he whose help is the God of Jacob, whose hope is in Yahweh his God.", tags: ["hope", "faith"], testament: "old" },
  { book: "Titus", chapter: 2, verse_start: 11, verse_end: 14, text: "For the grace of God has appeared, bringing salvation to all men, instructing us to deny ungodliness and worldly lusts and to live soberly, righteously, and godly in this present age, looking for the blessed hope and appearing of the glory of our great God and Savior, Jesus Christ, who gave himself for us, to redeem us from all lawlessness and to purify for himself a people for his own possession, zealous for good works.", tags: ["hope", "salvation", "grace"], testament: "new" },
  { book: "1 Peter", chapter: 1, verse_start: 3, text: "Blessed be the God and Father of our Lord Jesus Christ, who according to his great mercy gave us a new birth into a living hope through the resurrection of Jesus Christ from the dead", tags: ["hope", "salvation"], testament: "new" },
  { book: "1 Peter", chapter: 3, verse_start: 15, text: "But sanctify the Lord God in your hearts. Always be ready to give an answer to everyone who asks you a reason for the hope that is in you, with gentleness and fear.", tags: ["hope"], testament: "new" },
  { book: "Romans", chapter: 5, verse_start: 1, verse_end: 5, text: "Being therefore justified by faith, we have peace with God through our Lord Jesus Christ; through whom we also have our access by faith into this grace in which we stand. We rejoice in hope of the glory of God. Not only so, but we also rejoice in our tribulations, knowing that tribulation works perseverance; perseverance, proven character; and proven character, hope. And hope doesn't disappoint us, because God's love has been poured into our hearts through the Holy Spirit which was given to us.", tags: ["hope", "peace", "faith"], testament: "new" },

  // LOVE
  { book: "John", chapter: 3, verse_start: 16, text: "For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.", tags: ["love", "salvation", "faith"], testament: "new" },
  { book: "John", chapter: 15, verse_start: 13, verse_end: 17, text: "No one has greater love than this, that someone would lay down his life for his friends. You are my friends if you do whatever I command you. I have called you, that you may go and bear fruit, and that your fruit may remain, that whatever you will ask of the Father in my name, he may give it to you. This is my command: that you love one another.", tags: ["love"], testament: "new" },
  { book: "1 John", chapter: 4, verse_start: 7, verse_end: 11, text: "Beloved, let us love one another, for love is of God, and everyone who loves has been born of God and knows God. He who doesn't love doesn't know God, for God is love. In this was the love of God shown toward us, that God sent his one and only Son into the world that we might live through him. In this is love: not that we loved God, but that he loved us, and sent his Son to be the atoning sacrifice for our sins. Beloved, if God loved us this way, we also ought to love one another.", tags: ["love"], testament: "new" },
  { book: "1 John", chapter: 4, verse_start: 18, verse_end: 19, text: "There is no fear in love; but perfect love casts out fear, because fear has punishment. He who fears is not perfected in love. We love him, because he first loved us.", tags: ["love", "fear"], testament: "new" },
  { book: "Romans", chapter: 13, verse_start: 8, verse_end: 10, text: "Owe no one anything, except to love one another; for he who loves his neighbor has fulfilled the law. The commandments, 'You shall not commit adultery,' 'You shall not murder,' 'You shall not steal,' 'You shall not covet,' and whatever other commandments there are, are all summed up in this saying, namely, 'You shall love your neighbor as yourself.' Love doesn't harm a neighbor. Therefore love is the fulfillment of the law.", tags: ["love"], testament: "new" },
  { book: "Galatians", chapter: 5, verse_start: 13, verse_end: 14, text: "For you, brothers, were called for freedom. Only don't use your freedom as an opportunity for the flesh, but through love serve one another. For the whole law is fulfilled in one word, in this: 'You shall love your neighbor as yourself.'", tags: ["love"], testament: "new" },
  { book: "Colossians", chapter: 3, verse_start: 12, verse_end: 14, text: "Put on therefore, as God's chosen ones, holy and beloved, a heart of compassion, kindness, humility, gentleness, and patience; bearing with one another, and forgiving each other if any man has a complaint against any; even as Christ forgave you, so you also do. Above all these things, put on love, which is the bond of perfection.", tags: ["love", "grace"], testament: "new" },
  { book: "1 Corinthians", chapter: 13, verse_start: 1, verse_end: 13, text: "If I speak with the tongues of men and of angels, but have not love, I am a sounding brass, or a clanging cymbal. And if I have the gift of prophecy, and know all mysteries and all knowledge; and if I have all faith, so as to remove mountains, but have not love, I am nothing. And if I give all my goods to feed the poor, and if I give my body to be burned, but have not love, it profits me nothing. Love is patient. Love is kind. Love is not jealous. Love doesn't brag, is not proud, doesn't behave rudely, doesn't seek its own way, is not irritable, doesn't keep a record of wrongs; finds no delight in unrighteousness, but rejoices with the truth; bears all things, believes all things, hopes all things, endures all things. Love never ends. But where there are prophecies, they will be done away with. Where there are tongues, they will cease. Where there is knowledge, it will be done away with. For we know in part, and we prophesy in part; but when that which is complete has come, then that which is partial will be done away with. When I was a child, I spoke as a child, I thought as a child, I reasoned as a child. But when I became a man, I put away childish things. For now we see in a mirror, dimly, but then face to face. Now I know in part. Then I will know fully, even as I was also known fully. But now faith, hope, and love remain, these three. The greatest of these is love.", tags: ["love", "faith", "hope"], testament: "new" },
  { book: "Deuteronomy", chapter: 6, verse_start: 4, verse_end: 9, text: "Hear, Israel: Yahweh is our God. Yahweh is one. You shall love Yahweh your God with all your heart, and with all your soul, and with all your might. These words, which I command you today, shall be on your heart; and you shall teach them diligently to your children, and shall talk of them when you sit in your house, and when you walk by the way, and when you lie down, and when you rise up. You shall bind them for a sign on your hand, and they shall be for frontlets between your eyes. You shall write them on the doorposts of your house, and on your gates.", tags: ["love", "faith"], testament: "old" },
  { book: "Psalm", chapter: 136, verse_start: 1, text: "Give thanks to Yahweh, for he is good, for his loving kindness endures forever.", tags: ["love"], testament: "old" },

  // SALVATION
  { book: "Acts", chapter: 2, verse_start: 21, text: "It will be that whoever will call on the name of the Lord will be saved.", tags: ["salvation"], testament: "new" },
  { book: "Acts", chapter: 4, verse_start: 12, text: "There is salvation in none other, for neither is there any other name under heaven, that is given among men, by which we must be saved.", tags: ["salvation"], testament: "new" },
  { book: "Romans", chapter: 1, verse_start: 16, text: "For I am not ashamed of the Gospel of Christ, for it is the power of God for salvation to everyone who believes, to the Jew first, and also to the Greek.", tags: ["salvation", "faith"], testament: "new" },
  { book: "Romans", chapter: 10, verse_start: 9, text: "Because if you confess with your mouth that Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved.", tags: ["salvation", "faith"], testament: "new" },
  { book: "2 Timothy", chapter: 3, verse_start: 15, text: "and that from infancy you have known the sacred writings which are able to make you wise for salvation through faith which is in Christ Jesus.", tags: ["salvation", "faith", "wisdom"], testament: "new" },
  { book: "Titus", chapter: 3, verse_start: 4, verse_end: 7, text: "But when the kindness of God our Savior and his love toward mankind appeared, not by works of righteousness which we did, but according to his mercy, he saved us, through the washing of regeneration and renewing by the Holy Spirit, whom he poured out on us richly, through Jesus Christ our Savior; that, being justified by his grace, we might become heirs according to the hope of eternal life.", tags: ["salvation", "grace", "hope"], testament: "new" },
  { book: "Ephesians", chapter: 1, verse_start: 7, verse_end: 10, text: "In him we have redemption through his blood, the forgiveness of our trespasses, according to the riches of his grace, which he made to abound toward us in all wisdom and prudence, making known to us the mystery of his will, according to his good pleasure, which he purposed in him, to an administration of the fullness of the times, to sum up all things in Christ, both things in the heavens and things on the earth, in him, in whom also we were made a heritage, having been predestined according to the purpose of him who works all things after the counsel of his will", tags: ["salvation", "grace"], testament: "new" },
  { book: "Psalm", chapter: 27, verse_start: 1, text: "Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the stronghold of my life. Of whom shall I be afraid?", tags: ["salvation", "faith"], testament: "old" },
  { book: "Psalm", chapter: 62, verse_start: 1, verse_end: 2, text: "My soul waits in silence for God only. My salvation is from him. He alone is my rock and my salvation, my stronghold. I will never be shaken.", tags: ["salvation", "faith", "trust"], testament: "old" },
  { book: "Isaiah", chapter: 12, verse_start: 2, text: "Behold, God is my salvation. I will trust, and will not be afraid; for Yah, Yahweh, is my strength and song; and he has become my salvation.", tags: ["salvation", "faith", "strength"], testament: "old" },
  { book: "Isaiah", chapter: 53, verse_start: 5, verse_end: 6, text: "But he was wounded for our transgressions. He was bruised for our iniquities. The punishment for our peace was on him; and by his stripes we are healed. All we like sheep have gone astray. Everyone has turned to his own way; and Yahweh has laid on him the iniquities of us all.", tags: ["salvation", "grace"], testament: "old" },
  { book: "John", chapter: 10, verse_start: 9, verse_end: 10, text: "I am the door. If anyone enters through me, he will be saved, and will go in and out, and find pasture. The thief comes only to steal, kill, and destroy. I came that they may have life, and may have it abundantly.", tags: ["salvation", "life"], testament: "new" },

  // PEACE
  { book: "John", chapter: 14, verse_start: 27, text: "Peace I leave with you. My peace I give to you. Not as the world gives, I give to you. Don't let your heart be troubled, neither let it be fearful.", tags: ["peace"], testament: "new" },
  { book: "Romans", chapter: 14, verse_start: 17, text: "For the Kingdom of God is not eating and drinking, but righteousness, peace, and joy in the Holy Spirit.", tags: ["peace", "righteousness"], testament: "new" },
  { book: "Romans", chapter: 15, verse_start: 33, text: "Now the God of peace be with you all. Amen.", tags: ["peace"], testament: "new" },
  { book: "Philippians", chapter: 4, verse_start: 7, text: "And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.", tags: ["peace"], testament: "new" },
  { book: "Colossians", chapter: 3, verse_start: 15, text: "Let the peace of Christ rule in your hearts, to which also you were called in one body, and be thankful.", tags: ["peace"], testament: "new" },
  { book: "2 Thessalonians", chapter: 3, verse_start: 16, text: "Now may the Lord of peace himself give you peace at all times in all ways. The Lord be with you all.", tags: ["peace"], testament: "new" },
  { book: "Isaiah", chapter: 26, verse_start: 3, text: "You will keep in perfect peace him whose mind is steadfast, because he trusts in you.", tags: ["peace", "trust"], testament: "old" },
  { book: "Isaiah", chapter: 9, verse_start: 6, verse_end: 7, text: "For to us a child is born, to us a son is given; and the government will be on his shoulders. His name will be called Wonderful, Counselor, Mighty God, Everlasting Father, Prince of Peace. Of the increase of his government and of peace there will be no end, on the throne of David, and over his kingdom, to establish it, and to uphold it with justice and righteousness from that time on, even forever. The zeal of Yahweh of Armies will perform this.", tags: ["peace"], testament: "old" },
  { book: "Psalm", chapter: 34, verse_start: 14, text: "Depart from evil, and do good. Seek peace, and pursue it.", tags: ["peace"], testament: "old" },
  { book: "Psalm", chapter: 85, verse_start: 8, verse_end: 10, text: "I will hear what Yahweh God will speak, for he will speak peace to his people, to his saints, but let them not turn back to folly. Surely his salvation is near to those who fear him, that glory may dwell in our land. Mercy and truth have met together. Righteousness and peace have kissed each other.", tags: ["peace", "salvation"], testament: "old" },
  { book: "Numbers", chapter: 6, verse_start: 24, verse_end: 26, text: "Yahweh bless you, and keep you. Yahweh make his face to shine on you, and be gracious to you. Yahweh lift up his face to you, and give you peace.", tags: ["peace"], testament: "old" },

  // STRENGTH
  { book: "Isaiah", chapter: 40, verse_start: 28, verse_end: 31, text: "Have you not known? Have you not heard? The everlasting God, Yahweh, the Creator of the ends of the earth, doesn't faint, neither is weary. There is no searching of his understanding. He gives power to the faint. He increases the strength of those who have no might. Even the youths shall faint and be weary, and the young men shall utterly fall: but those who wait for Yahweh shall renew their strength. They shall mount up with wings as eagles. They shall run, and not be weary. They shall walk, and not faint.", tags: ["strength", "hope", "trust"], testament: "old" },
  { book: "Psalm", chapter: 46, verse_start: 1, text: "God is our refuge and strength, a very present help in trouble.", tags: ["strength", "trust"], testament: "old" },
  { book: "Psalm", chapter: 118, verse_start: 14, text: "Yahweh is my strength and song. He has become my salvation.", tags: ["strength", "salvation"], testament: "old" },
  { book: "Exodus", chapter: 15, verse_start: 2, text: "Yahweh is my strength and song, and he has become my salvation: this is my God, and I will praise him; my father's God, and I will exalt him.", tags: ["strength", "salvation"], testament: "old" },
  { book: "2 Chronicles", chapter: 16, verse_start: 9, text: "For the eyes of Yahweh run to and fro throughout the whole earth, to show himself strong in the behalf of those whose heart is blameless toward him. In this you have done foolishly; for from now on you will have wars.", tags: ["strength"], testament: "old" },
  { book: "Deuteronomy", chapter: 33, verse_start: 25, text: "Your bars are iron and brass. As your days, so is your strength.", tags: ["strength"], testament: "old" },
  { book: "Psalm", chapter: 73, verse_start: 26, text: "My flesh and my heart fails, but God is the strength of my heart and my portion forever.", tags: ["strength", "trust"], testament: "old" },
  { book: "Philippians", chapter: 4, verse_start: 13, text: "I can do all things through Christ, who strengthens me.", tags: ["strength"], testament: "new" },
  { book: "2 Timothy", chapter: 4, verse_start: 17, text: "But the Lord stood by me, and gave me power, that through me the message might be fully proclaimed, and all the Gentiles might hear. And I was delivered out of the mouth of the lion.", tags: ["strength"], testament: "new" },
  { book: "1 Peter", chapter: 4, verse_start: 11, text: "If anyone speaks, let it be as it were, the very words of God. If anyone serves, let it be as of the strength which God supplies, that in all things God may be glorified through Jesus Christ, to whom be the glory and the dominion forever and ever. Amen.", tags: ["strength", "grace"], testament: "new" },
  { book: "Ephesian", chapter: 6, verse_start: 10, verse_end: 11, text: "Finally, be strong in the Lord, and in the strength of his might. Put on the whole armor of God, that you may be able to stand against the wiles of the devil.", tags: ["strength"], testament: "new" },

  // GRACE
  { book: "2 Corinthians", chapter: 12, verse_start: 9, text: "He has said to me, My grace is sufficient for you, for my power is made perfect in weakness. Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me.", tags: ["grace", "strength"], testament: "new" },
  { book: "Romans", chapter: 5, verse_start: 1, verse_end: 2, text: "Being therefore justified by faith, we have peace with God through our Lord Jesus Christ; through whom we also have our access by faith into this grace in which we stand, and rejoice in hope of the glory of God.", tags: ["grace", "faith", "peace", "hope"], testament: "new" },
  { book: "Romans", chapter: 11, verse_start: 6, text: "But if by grace, it is no longer by works; otherwise grace is no longer grace.", tags: ["grace"], testament: "new" },
  { book: "Ephesians", chapter: 2, verse_start: 8, text: "For by grace you have been saved through faith, and that not of yourselves; it is the gift of God", tags: ["grace", "faith", "salvation"], testament: "new" },
  { book: "Titus", chapter: 2, verse_start: 11, text: "For the grace of God has appeared, bringing salvation to all men", tags: ["grace", "salvation"], testament: "new" },
  { book: "2 Timothy", chapter: 1, verse_start: 9, text: "who has saved us and called us with a holy calling, not according to our works, but according to his own purpose and grace, which was given to us in Christ Jesus before times eternal", tags: ["grace", "salvation"], testament: "new" },
  { book: "Acts", chapter: 15, verse_start: 11, text: "But we believe that we will be saved through the grace of the Lord Jesus", tags: ["grace", "salvation"], testament: "new" },
  { book: "1 Peter", chapter: 5, verse_start: 10, text: "But the God of all grace, who has called you to his eternal glory in Christ Jesus, after you have suffered a little while, will himself perfect, establish, strengthen, and settle you.", tags: ["grace", "strength"], testament: "new" },
  { book: "James", chapter: 4, verse_start: 6, text: "But he gives more grace. Therefore it says, God resists the proud, but gives grace to the humble.", tags: ["grace"], testament: "new" },
  { book: "John", chapter: 1, verse_start: 14, verse_end: 17, text: "The Word became flesh, and lived among us, and we saw his glory, glory as of the only Son of the Father. The Word became flesh, and lived among us. From his fullness we all received, and grace for grace. For the law was given through Moses. Grace and truth came through Jesus Christ.", tags: ["grace", "truth"], testament: "new" },
  { book: "Psalm", chapter: 84, verse_start: 11, text: "For Yahweh God is a sun and a shield. Yahweh will give grace and glory. No good thing will he withhold from those who walk uprightly.", tags: ["grace"], testament: "old" },

  // TRUST
  { book: "Proverbs", chapter: 3, verse_start: 5, verse_end: 6, text: "Trust in Yahweh with all your heart, and don't lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.", tags: ["trust", "wisdom"], testament: "old" },
  { book: "Psalm", chapter: 37, verse_start: 3, text: "Trust in Yahweh, and do good. Dwell in the land, and feed on his faithfulness.", tags: ["trust", "faith"], testament: "old" },
  { book: "Psalm", chapter: 56, verse_start: 3, verse_end: 4, text: "When I am afraid, I will trust in you. In God, whose word I praise, in God I trust. I will not be afraid. What can flesh do to me?", tags: ["trust", "fear"], testament: "old" },
  { book: "Psalm", chapter: 91, verse_start: 1, verse_end: 2, text: "He who dwells in the secret place of the Most High will rest in the shadow of the Almighty. I will say of Yahweh, He is my refuge and my fortress, my God, in whom I trust.", tags: ["trust", "faith"], testament: "old" },
  { book: "Psalm", chapter: 115, verse_start: 9, verse_end: 11, text: "Israel, trust in Yahweh. He is their help and their shield. House of Aaron, trust in Yahweh. He is their help and their shield. You who fear Yahweh, trust in Yahweh. He is their help and their shield.", tags: ["trust", "faith"], testament: "old" },
  { book: "Jeremiah", chapter: 17, verse_start: 7, verse_end: 8, text: "Blessed is the man who trusts in Yahweh, and whose confidence is in Yahweh. For he will be as a tree planted by the waters, that spreads out its roots by the river, and will not fear when heat comes. Its leaf will be green. In the year of drought it won't be anxious, and won't cease from yielding fruit.", tags: ["trust", "hope"], testament: "old" },
  { book: "Habakkuk", chapter: 2, verse_start: 4, text: "Behold, his soul is puffed up; it is not upright in him; but the righteous will live by his faith.", tags: ["trust", "faith"], testament: "old" },
  { book: "Numbers", chapter: 20, verse_start: 12, text: "Yahweh said to Moses and Aaron, Because you didn't believe me, to sanctify me in the eyes of the children of Israel, therefore you will not bring this assembly into the land which I have given them.", tags: ["trust"], testament: "old" },
  { book: "2 Kings", chapter: 18, verse_start: 20, text: "But they were only a blast of lips. And these are the words that the Pharaoh king of Egypt sent to us. But you say, I trust in the word of my hand. Now consider how I have made you able to trust.", tags: ["trust"], testament: "old" },
  { book: "Romans", chapter: 14, verse_start: 22, text: "The faith which you have, have as your own conviction before God. Happy is he who doesn't judge himself in what he approves.", tags: ["trust", "faith"], testament: "new" },
  { book: "2 Timothy", chapter: 1, verse_start: 12, text: "For this cause I also suffer these things, but I am not ashamed, for I know him whom I have believed, and I am persuaded that he is able to guard that which I have committed to him against that day.", tags: ["trust", "faith"], testament: "new" },
  { book: "1 John", chapter: 3, verse_start: 19, verse_end: 20, text: "And by this we will know that we are of the truth, and will assure our hearts before him, because if our heart condemns us, God is greater than our heart, and knows all things.", tags: ["trust"], testament: "new" },

  // WISDOM
  { book: "Proverbs", chapter: 1, verse_start: 7, text: "The fear of Yahweh is the beginning of knowledge; but the foolish despise wisdom and instruction.", tags: ["wisdom", "faith"], testament: "old" },
  { book: "Proverbs", chapter: 2, verse_start: 1, verse_end: 6, text: "My son, if you will receive my words, and store up my commandments within you, so that you make your ear attend to wisdom, and apply your heart to understanding; yes, if you call out for discernment, and raise your voice for understanding; if you seek her like silver, and search for her like a hidden treasure; then you will understand the fear of Yahweh, and find the knowledge of God. For Yahweh gives wisdom. Out of his mouth comes knowledge and understanding.", tags: ["wisdom", "knowledge"], testament: "old" },
  { book: "Proverbs", chapter: 3, verse_start: 13, verse_end: 18, text: "Happy is the man who finds wisdom, and the man who gets understanding. For her income is better than silver, and her yield better than gold. She is more precious than rubies. None of the things you can desire are comparable to her. Length of days is in her right hand. In her left hand are riches and honor. Her ways are ways of pleasantness, and all her paths are peace. She is a tree of life to those who lay hold of her. Those who hold her fast are called happy.", tags: ["wisdom", "peace"], testament: "old" },
  { book: "Proverbs", chapter: 4, verse_start: 5, verse_end: 7, text: "Get wisdom. Get understanding. Don't forget, neither turn away from the words of my mouth. Don't forsake her, and she will preserve you. Love her, and she will keep you. Wisdom is the supreme thing. Therefore get wisdom. With all your getting, get understanding.", tags: ["wisdom"], testament: "old" },
  { book: "Proverbs", chapter: 9, verse_start: 10, text: "The fear of Yahweh is the beginning of wisdom. The knowledge of the Holy One is understanding.", tags: ["wisdom", "understanding"], testament: "old" },
  { book: "Ecclesiastes", chapter: 7, verse_start: 12, text: "Wisdom is a shelter, as money is a shelter; but the advantage of knowledge is this, that wisdom preserves the life of its owners.", tags: ["wisdom"], testament: "old" },
  { book: "Daniel", chapter: 2, verse_start: 20, verse_end: 23, text: "Daniel said, Let the name of God be blessed forever and ever, for wisdom and might are his. He changes times and seasons. He removes kings, and sets up kings. He gives wisdom to the wise, and knowledge to those who have understanding. He reveals the deep and secret things. He knows what is in the darkness, and the light dwells with him. I thank you and praise you, God of my fathers, who have given me wisdom and might, and have now made known to me what we asked of you, for you have made known to us the king's matter.", tags: ["wisdom"], testament: "old" },
  { book: "James", chapter: 1, verse_start: 5, text: "If any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproof, and it will be given to him.", tags: ["wisdom", "prayer"], testament: "new" },
  { book: "Colossians", chapter: 1, verse_start: 9, verse_end: 10, text: "For this cause, we also, since the day we heard it, haven't ceased to pray and make requests for you, that you may be filled with the knowledge of his will in all spiritual wisdom and understanding, that you may walk worthily of the Lord, pleasing him in all respects, bearing fruit in every good work, and increasing in the knowledge of God", tags: ["wisdom", "knowledge"], testament: "new" },
  { book: "1 Corinthians", chapter: 1, verse_start: 18, verse_end: 25, text: "For the word of the cross is foolishness to those who are dying, but to us who are being saved it is the power of God. For it is written, I will destroy the wisdom of the wise, and the understanding of the intelligent I will bring to nothing. Where is the wise? Where is the scribe? Where is the debater of this age? Hasn't God made foolish the wisdom of the world? For seeing that in the wisdom of God, the world through its wisdom didn't know God, it pleased God through the foolishness of the preaching to save those who believe. Jews ask for signs, and Greeks seek after wisdom, but we preach Christ crucified, to the Jews a stumbling block, and to the Greeks foolishness; but to those who are called, both Jews and Greeks, Christ is the power of God and the wisdom of God. Because the foolishness of God is wiser than men, and the weakness of God is stronger than men.", tags: ["wisdom"], testament: "new" },
  { book: "Romans", chapter: 11, verse_start: 33, verse_end: 36, text: "Oh the depth of the riches both of the wisdom and the knowledge of God! How unsearchable are his judgments, and his paths past tracing out! For who has known the mind of the Lord? Or who has been his counselor? Or who has first given to him, and it will be repaid to him? For of him, and through him, and to him, are all things. To him be the glory forever! Amen.", tags: ["wisdom", "knowledge"], testament: "new" },
];

async function seedScriptures() {
  console.log("Starting scripture seeding...");

  const { error } = await supabase.from("scriptures").upsert(
    scriptures.map((s) => ({
      book: s.book,
      chapter: s.chapter,
      verse_start: s.verse_start,
      verse_end: s.verse_end,
      text: s.text,
      tags: s.tags,
      testament: s.testament,
    })),
    { onConflict: "book,chapter,verse_start" }
  );

  if (error) {
    console.error("Error seeding scriptures:", error);
    process.exit(1);
  }

  console.log(`Successfully seeded ${scriptures.length} scriptures`);
}

seedScriptures().catch(console.error);